# .circleci/config.yml
version: 2.1

orbs:
  slack: circleci/slack@1.0.0
  
jobs:
  build:
    working_directory: ~/Beauty.jl

    docker:
      - image: quantumfactory/buildbot-julia:version1.0.test

    steps:
      - checkout
      
      - restore_cache:
          key: julia

      - run:
          name: Test Package in Julia
          command: julia --project=. -e "import Pkg; Pkg.test()"
          
      - run:
          name: Build Documentation
          command: julia --project=. docs/make.jl          

      - save_cache:
          key: julia
          paths:
            - "~/.julia"
        
      - store_artifacts:
          path: docs/build
          destination: docs

      - add_ssh_keys:
          fingerprints:
            - "94:6c:f0:23:54:54:1a:43:98:82:1b:52:a5:5a:7a:ea"

      - run:
          name: Upload Documentation
          command: |
            echo '|1|yJb8jCN4ACKhZLRcjEDWtl8Sggw=|34y5wac1TTSLjdbucmsCa4QRBXc= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAGp1W0jQ217mdjE0OvggNr/wg9kHYYgmlTcA/ObLKN5bCtPpMJGDdm/vAYbSFaBtHHiOAQQmPg6LejJuOhk7Zo=' >> ~/.ssh/known_hosts;
            echo '|1|tp9BACZM+M5CHExCa2MznI7STj4=|J46emfS0L55ZuhyUI6vxLhA2pqk= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDypicw6GdbqBGMXgcrXoxRNUyOJWRBzv06a2TMlO7fQ34OSiekvBcJue7HLnFNYUpqlr7SHKynK8OcP8pFMntJEoDgIboWuFCphZhzEfBSjpryNF/Cp8jpF4vswi42FpbWCsooGn9NuXmW0isoCWQVEz73412gSvFnbgG/s8JSf21wlVl1yUDBI6m5btrikhGU34movU/3qQy44x/02pvBVAenTaSfH2IyjayUpr7vb0fF/inNCebmDAKitJ5vbfmVuoCYcZ0P+KSuR7XjVuFa2SbS5AJbUwKRj31tw4Fd1I1yii3XBKYm5DygkVCSIfTvu7Qi/B4nE97RymtSp5cr' >> ~/.ssh/known_hosts;
            echo '|1|dhkE9c7oL8H3OVgPs0HgWh6i2Hw=|0ZHcUZDlDmMyWdN4qt3oPoxksZg= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILFrePFd+1xbvJivY6MdInlhY3x1F3DiazzTswAyHjvt' >> ~/.ssh/known_hosts;
            mv docs/build docs/Beauty.jl && echo -e 'put -r docs/Beauty.jl' | sftp -P $SSH_PORT $SSH_USER@$SSH_HOST:docs/github.com/Quantum-Factory

      - slack/status:
          fail_only: "false"

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: default
